# Generated by Django 4.1.7 on 2023-07-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_openai_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='openai_key',
            field=models.CharField(blank=True, max_length=50000),
        ),
    ]
